#!/usr/bin/env php
<?php

set_time_limit(0);

use Tomahawk\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

require_once __DIR__ . '/autoload.php';
require_once __DIR__.'/AppKernel.php';

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('TOMAHAWK_ENV') ?: 'dev');
$debug = getenv('TOMAHAWK_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);

$application = new Application($kernel);

$application->run($input);